export const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAILURE = "GET_USER_PROFILE_FAILURE";

export const GET_REPOSITORIES_REQUEST = "GET_REPOSITORIES_REQUEST";
export const GET_REPOSITORIES_SUCCESS = "GET_REPOSITORIES_SUCCESS";
export const GET_REPOSITORIES_FAILURE = "GET_REPOSITORIES_FAILURE";

export const FILTER_REPOSITORIES_REQUEST = "FILTER_REPOSITORIES_REQUEST";
export const RESET_FILTER_REPOSITORIES_REQUEST = "RESET_FILTER_REPOSITORIES_REQUEST";
